In [1]:
import numpy as np

In [2]:
# cria uma matriz unidimensional
mt = np.array([12,24,36,48])
print(mt)
print(type(mt))

[12 24 36 48]
<class 'numpy.ndarray'>


In [3]:
# criar com um tipo especifico
mtfloat = np.array([12,24,36,48], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))

[12. 24. 36. 48.]
<class 'numpy.ndarray'>


In [8]:
# mudar a tipagem
mtnew = np.array([1,2,3.55,5.66,7.1345])
print(mtnew)

# Truncado

mtnewint = mtnew.astype(np.int64)
print(mtnewint)

[1.     2.     3.55   5.66   7.1345]
[1 2 3 5 7]
